# Generated by Django 2.2.6 on 2019-10-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='new',
            field=models.TextField(default=True),
        ),
    ]
