# Generated by Django 2.2.6 on 2019-10-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='new',
        ),
    ]
